"""Configuration for Snap to Dust."""
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent

CAMERA_INDEX = 0
FRAME_WIDTH = 1280
FRAME_HEIGHT = 720
WINDOW_NAME = "Snap to Dust - Real-Time Human Disintegration"

MODEL_PATH = str(ROOT_DIR / "models" / "yolov8n-seg.pt")
MODEL_FALLBACK = "yolov8n-seg.pt"
HAND_MODEL_PATH = str(ROOT_DIR / "models" / "hand_landmarker.task")
YOLO_IMGSZ = 640
YOLO_CONFIDENCE = 0.45
YOLO_DEVICE = ""  # Empty selects CUDA when available through Ultralytics, otherwise CPU.
SEGMENTATION_INTERVAL = 5
MASK_BLUR_KERNEL = 5
MASK_DILATION = 3

MAX_PARTICLES = 12000
PARTICLE_SAMPLE_STEP = 2
DUST_DURATION = 2.5
RECONSTRUCT_DURATION = 2.0
RECONSTRUCT_FADE_IN = 0.35
FREEZE_DURATION = 0.12
WIND_X = 0.18
WIND_Y = -0.08
GRAVITY = 0.018
TURBULENCE = 0.11
PARTICLE_DRAG = 0.985
PARTICLE_MIN_LIFE = 0.8
PARTICLE_MAX_LIFE = 1.6
PARTICLE_MIN_SIZE = 0.6
PARTICLE_MAX_SIZE = 2.4

SNAP_COOLDOWN = 1.5
SNAP_HISTORY_SIZE = 12
SNAP_CLOSE_DISTANCE = 0.26
SNAP_RELEASE_DISTANCE = 0.42
SNAP_APPROACH_SPEED = -0.008
SNAP_SEPARATION_SPEED = 0.025
SNAP_MIN_HAND_SCALE = 0.03

ENABLE_REAPPEAR = False
REAPPEAR_DELAY = 9.0
ENABLE_SOUND = False
ENABLE_CAMERA_SHAKE = True
ENABLE_FLASH = True
DEBUG_MODE = True
SHOW_MASK = False

FPS_SMOOTHING = 0.9
RNG_SEED = 7
